# Generated by Django 6.0.6 on 2026-07-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name_arabic', models.TextField()),
                ('name_bangla', models.TextField()),
                ('name_english', models.TextField()),
                ('total_ayah', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'surah',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_text', models.TextField(unique=True)),
                ('normalized_text', models.TextField(blank=True, editable=False)),
                ('is_meaning_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'word',
            },
        ),
        migrations.CreateModel(
            name='Ruku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruku_number', models.PositiveSmallIntegerField(unique=True)),
                ('surah_ruku_number', models.PositiveSmallIntegerField()),
                ('first_verse_id', models.PositiveIntegerField()),
                ('last_verse_id', models.PositiveIntegerField()),
                ('verses_count', models.PositiveIntegerField()),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rukus', to='quran.surah')),
            ],
            options={
                'db_table': 'ruku',
                'ordering': ['ruku_number'],
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_number', models.PositiveIntegerField()),
                ('verse_key', models.CharField(max_length=10, unique=True)),
                ('arabic_text', models.TextField()),
                ('translation_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ayahs', to='quran.ruku')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.surah')),
            ],
            options={
                'db_table': 'ayah',
                'ordering': ['surah__number', 'ayah_number'],
            },
        ),
        migrations.CreateModel(
            name='WordMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning_text', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='quran.word')),
            ],
            options={
                'db_table': 'word_meaning',
            },
        ),
        migrations.CreateModel(
            name='WordNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning_basra', models.TextField(blank=True)),
                ('meaning_kufa', models.TextField(blank=True)),
                ('root', models.CharField(blank=True, max_length=100)),
                ('part_of_speech', models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('particle', 'Particle'), ('other', 'Other')], max_length=20)),
                ('verb_form', models.CharField(blank=True, max_length=50)),
                ('morphology', models.CharField(blank=True, max_length=255)),
                ('derived_forms', models.TextField(blank=True)),
                ('lemma', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='quran.word')),
            ],
            options={
                'db_table': 'word_note',
            },
        ),
        migrations.CreateModel(
            name='WordOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_occurrences', to='quran.ayah')),
                ('meaning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='quran.wordmeaning')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='quran.word')),
            ],
            options={
                'db_table': 'word_occurrence',
                'ordering': ['ayah', 'position'],
                'constraints': [models.UniqueConstraint(fields=('ayah', 'position'), name='unique_ayah_position')],
            },
        ),
    ]
