# Generated by Django 6.0.6 on 2026-08-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordnote',
            name='lemma',
        ),
        migrations.RemoveField(
            model_name='wordnote',
            name='morphology',
        ),
        migrations.RemoveField(
            model_name='wordnote',
            name='note',
        ),
        migrations.RemoveField(
            model_name='wordnote',
            name='part_of_speech',
        ),
        migrations.RemoveField(
            model_name='wordnote',
            name='verb_form',
        ),
        migrations.AddField(
            model_name='wordnote',
            name='grammatical_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wordnote',
            name='meaning_baghdad',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wordnote',
            name='note_for_pattern',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wordnote',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wordnote',
            name='pattern',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wordnote',
            name='root',
            field=models.TextField(blank=True),
        ),
    ]
