# Generated by Django 6.0.6 on 2026-08-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_remove_wordnote_lemma_remove_wordnote_morphology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordnote',
            name='derived_forms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
