# Generated by Django 6.0.6 on 2026-08-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_alter_wordnote_derived_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordoccurrence',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
    ]
