# Generated by Django 6.0.6 on 2026-08-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='revelation_place',
            field=models.CharField(blank=True, choices=[('makkah', 'Makkah'), ('madinah', 'Madinah')], max_length=10),
        ),
    ]
