# Generated by Django 6.0.6 on 2026-09-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0007_rename_name_bangla_to_meaning_bangla'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='content_changed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
